name = input("ENTER YOUR NAME: ")
branch = input("ENTER YOUR BRANCH: ")
gender = input("ENTER YOUR GENDER: ")
collegename = input("ENTER YOUR COLLEGE NAME: ")
age = int(input("ENTER YOUR AGE: "))
print("Name: ",name)
print("Branch: ",branch)
print("Gender: ",gender)
print("Collegename: ",collegename)
print("Age: ",age)
